# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fallingmeat/projects/bezier/class

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fallingmeat/projects/bezier/class

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fallingmeat/projects/bezier/class/CMakeFiles /home/fallingmeat/projects/bezier/class/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fallingmeat/projects/bezier/class/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bezier

# Build rule for target.
bezier: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bezier
.PHONY : bezier

# fast build rule for target.
bezier/fast:
	$(MAKE) -f CMakeFiles/bezier.dir/build.make CMakeFiles/bezier.dir/build
.PHONY : bezier/fast

#=============================================================================
# Target rules for targets named btest

# Build rule for target.
btest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 btest
.PHONY : btest

# fast build rule for target.
btest/fast:
	$(MAKE) -f CMakeFiles/btest.dir/build.make CMakeFiles/btest.dir/build
.PHONY : btest/fast

bezier.o: bezier.cpp.o
.PHONY : bezier.o

# target to build an object file
bezier.cpp.o:
	$(MAKE) -f CMakeFiles/bezier.dir/build.make CMakeFiles/bezier.dir/bezier.cpp.o
.PHONY : bezier.cpp.o

bezier.i: bezier.cpp.i
.PHONY : bezier.i

# target to preprocess a source file
bezier.cpp.i:
	$(MAKE) -f CMakeFiles/bezier.dir/build.make CMakeFiles/bezier.dir/bezier.cpp.i
.PHONY : bezier.cpp.i

bezier.s: bezier.cpp.s
.PHONY : bezier.s

# target to generate assembly for a file
bezier.cpp.s:
	$(MAKE) -f CMakeFiles/bezier.dir/build.make CMakeFiles/bezier.dir/bezier.cpp.s
.PHONY : bezier.cpp.s

btest.o: btest.cpp.o
.PHONY : btest.o

# target to build an object file
btest.cpp.o:
	$(MAKE) -f CMakeFiles/btest.dir/build.make CMakeFiles/btest.dir/btest.cpp.o
.PHONY : btest.cpp.o

btest.i: btest.cpp.i
.PHONY : btest.i

# target to preprocess a source file
btest.cpp.i:
	$(MAKE) -f CMakeFiles/btest.dir/build.make CMakeFiles/btest.dir/btest.cpp.i
.PHONY : btest.cpp.i

btest.s: btest.cpp.s
.PHONY : btest.s

# target to generate assembly for a file
btest.cpp.s:
	$(MAKE) -f CMakeFiles/btest.dir/build.make CMakeFiles/btest.dir/btest.cpp.s
.PHONY : btest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bezier"
	@echo "... btest"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bezier.o"
	@echo "... bezier.i"
	@echo "... bezier.s"
	@echo "... btest.o"
	@echo "... btest.i"
	@echo "... btest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

